### PR TITLE
fix for getNotifications query

### LINKED ISSUE #65: Fix getNotifications prisma action
Need to find a way to replicate this query in prisma syntax: 
```
select * from spotifyre.suggestions where playlistid in (
select playlistid from spotifyre.playlists where userid = 'my_userid'
)
```

### PR DESCRIPTION
**Pull request by awave1**
Updated `prisma` and the schema, changed the query to use prisma's `include`.

closes #65

### CODE REVIEW

**Comment by awave1** [comment]
forgot to mention, you'll need to add `?schema=spotifyre` to the `POSTGRES_URL` in your `.env` file

File: server/src/actions/notifications.ts [hunk 1]
```diff
@@ -1,20 +1,26 @@
...
+    const result = await prisma.playlists.findMany({
+      where: {
+        userid: userID
+      },
+      include: {
+        suggestions: true
+      }
+    });
+
+    return result.flatMap(({ suggestions }) => suggestions);
```
Comment (awave1) [inline server/src/actions/notifications.ts:21]: thought I'll be able to get this using primsa query, but it wouldn't let me do this:
```ts
await prisma.suggestions.findMany({
  where: {
    userid: userID
  },
  include: {
    playlists: {
      where: {
        userid: userID
      }
    }
  }
});
```

**Review by natekchua — APPROVED** [review]
Lovely work my friend!
